#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# In case of problems in with IDE git UI and NVM: 
# https://typicode.github.io/husky/how-to.html#node-version-managers-and-guis

npx --no -- commitlint --edit ${1}
