name: Commit Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - name: Run linter
        uses: wearerequired/lint-action@v2
        with:
          xo: true

  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
