name: Lint and test files

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 16
          - 14
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run ci:test

      - name: Run linter
        if: (success() || failure())
        uses: wearerequired/lint-action@v2
        with:
          xo: true

      - name: Comment PR with coverage info
        if: github.event_name == 'pull_request' && (success() || failure())
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          clover-file: ./coverage/clover.xml
