name: Lint and test files

on:
  push:
    branches:
      - master
  pull_request:
    branches: ['**']

env:
  HUSKY: 0

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 18
          - 16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run ci:test

      - name: Comment PR with coverage info (only for node v20)
        if: github.event_name == 'pull_request' && matrix.node-version == 20 (success() || failure())
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: ./coverage/clover.xml
